---
apiVersion: automation.ace.io/v1alpha1
kind: AutomationPlatform
metadata:
  name: ace
  namespace: ace
spec:
  gateway:
    external_url: https://ace.example.com
  controller:
    enabled: true
  hub:
    enabled: true
  eda:
    enabled: true
  postgres:
    managed: true
    storage_size: 20Gi
  redis:
    managed: true
