---
- name: Render the Galaxy CR
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'galaxy.yaml.j2') | from_yaml }}"

- name: Patch up the hub's NetworkPolicies for vanilla Kubernetes
  kubernetes.core.k8s:
    state: present
    definition: "{{ item }}"
  loop: "{{ lookup('template', 'netpol.yaml.j2') | from_yaml_all | list }}"
  loop_control:
    label: "{{ item.metadata.name }}"
